"""add source_id to crawl_tasks

Revision ID: 0a946c4cac4a
Revises: 
Create Date: 2026-06-05 17:42:39.774082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a946c4cac4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_schedule_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', 'timeout', 'cancelled'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务执行历史表'
    )
    op.create_index('idx_csr_schedule_id', 'crawl_schedule_runs', ['schedule_id'], unique=False)
    op.create_index('idx_csr_started_at', 'crawl_schedule_runs', ['started_at'], unique=False)
    op.create_index('idx_csr_status', 'crawl_schedule_runs', ['status'], unique=False)
    op.create_table('crawl_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('full', 'incremental', 'targeted', 'health_check', 'cleanup'), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=True),
    sa.Column('target_config', sa.JSON(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_interval', sa.Integer(), nullable=False),
    sa.Column('concurrent_limit', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('notify_on_success', sa.Boolean(), nullable=False),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=False),
    sa.Column('notify_emails', sa.JSON(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('success_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.Enum('success', 'failed', 'running', 'timeout'), nullable=True),
    sa.Column('last_run_duration', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='定时任务配置表'
    )
    op.create_index('idx_csch_enabled', 'crawl_schedules', ['is_enabled'], unique=False)
    op.create_index('idx_csch_next_run', 'crawl_schedules', ['next_run_at'], unique=False)
    op.create_index('idx_csch_task_type', 'crawl_schedules', ['task_type'], unique=False)
    op.create_table('crawl_source_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False, comment='爬取源ID'),
    sa.Column('stat_date', sa.Date(), nullable=False, comment='统计日期'),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('success_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('timeout_requests', sa.Integer(), nullable=False),
    sa.Column('rate_limited_requests', sa.Integer(), nullable=False),
    sa.Column('persons_extracted', sa.Integer(), nullable=False),
    sa.Column('works_extracted', sa.Integer(), nullable=False),
    sa.Column('relations_extracted', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('min_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('max_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('p95_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('avg_completeness', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=False, comment='总耗时(秒)'),
    sa.Column('data_size_mb', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'stat_date', name='uk_source_date'),
    comment='爬取源日统计表'
    )
    op.create_index('idx_css_source_id', 'crawl_source_stats', ['source_id'], unique=False)
    op.create_index('idx_css_stat_date', 'crawl_source_stats', ['stat_date'], unique=False)
    op.create_table('crawl_sources',
    sa.Column('id', sa.String(length=32), nullable=False, comment='唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='源名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='源编码'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='源类型'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='基础URL'),
    sa.Column('config', sa.JSON(), nullable=True, comment='源配置'),
    sa.Column('request_interval', sa.DECIMAL(precision=3, scale=1), nullable=False, comment='请求间隔(秒)'),
    sa.Column('daily_limit', sa.Integer(), nullable=False, comment='每日请求上限'),
    sa.Column('concurrent_limit', sa.Integer(), nullable=False, comment='并发数限制'),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', 'deprecated'), nullable=False),
    sa.Column('health_status', sa.Enum('healthy', 'degraded', 'down'), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('total_requests', sa.BigInteger(), nullable=False),
    sa.Column('total_success', sa.BigInteger(), nullable=False),
    sa.Column('total_failed', sa.BigInteger(), nullable=False),
    sa.Column('avg_response_time', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='爬取源配置表'
    )
    op.create_index('idx_cs_health', 'crawl_sources', ['health_status'], unique=False)
    op.create_index('idx_cs_status', 'crawl_sources', ['status'], unique=False)
    op.create_index('idx_cs_type', 'crawl_sources', ['type'], unique=False)
    op.drop_index(op.f('version'), table_name='schema_migrations')
    op.drop_table('schema_migrations')
    op.alter_column('admin_users', 'role',
               existing_type=mysql.ENUM('super_admin', 'data_admin', 'operator', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'operator'"))
    op.alter_column('admin_users', 'permissions',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='æ\x9dƒé™\x90åˆ—è¡¨',
               existing_nullable=True)
    op.alter_column('admin_users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('admin_users', 'last_login_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('admin_users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admin_users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_is_active'), table_name='admin_users')
    op.drop_index(op.f('idx_role'), table_name='admin_users')
    op.drop_index(op.f('idx_username'), table_name='admin_users')
    op.create_index('idx_au_is_active', 'admin_users', ['is_active'], unique=False)
    op.create_index('idx_au_role', 'admin_users', ['role'], unique=False)
    op.create_index('idx_au_username', 'admin_users', ['username'], unique=False)
    op.create_table_comment(
        'admin_users',
        '管理员用户表',
        existing_comment='ç®¡ç\x90†å‘˜ç”¨æˆ·è¡¨',
        schema=None
    )
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='æ“\x8dä½œç”¨æˆ·',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='æ“\x8dä½œï¼šCREATE/UPDATE/DELETE/LOGIN',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='èµ„æº\x90ç±»åž‹ï¼šperson/work/relation',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='èµ„æº\x90ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='ä¿®æ”¹å‰\x8dçš„å€¼',
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_values',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='ä¿®æ”¹å\x90Žçš„å€¼',
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_resource'), table_name='audit_logs')
    op.drop_index(op.f('idx_user_id'), table_name='audit_logs')
    op.create_index('idx_al_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_al_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_al_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_al_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table_comment(
        'audit_logs',
        '审计日志表',
        existing_comment='å®¡è®¡æ—¥å¿—è¡¨',
        schema=None
    )
    op.add_column('crawl_logs', sa.Column('source_id', sa.String(length=32), nullable=True, comment='爬取源ID'))
    op.add_column('crawl_logs', sa.Column('stage', sa.String(length=50), nullable=True, comment='阶段: fetch/parse/validate/store'))
    op.add_column('crawl_logs', sa.Column('details', sa.JSON(), nullable=True, comment='详细日志信息'))
    op.alter_column('crawl_logs', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='ä»»åŠ¡ID',
               existing_nullable=False)
    op.alter_column('crawl_logs', 'level',
               existing_type=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'DEBUG', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'INFO'"))
    op.alter_column('crawl_logs', 'resource_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='çˆ¬å\x8f–URL',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'resource_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='èµ„æº\x90å\x90\x8dç§°',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'resource_type',
               existing_type=mysql.ENUM('person', 'work', 'page', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='èµ„æº\x90ç±»åž‹',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='æ“\x8dä½œï¼šdownload, parse, store, skip',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'status',
               existing_type=mysql.ENUM('success', 'failed', 'retry', 'pending', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='çŠ¶æ€\x81',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'duration_ms',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è€—æ—¶(ms)',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='æ—¥å¿—æ¶ˆæ\x81¯',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'error_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='é”™è¯¯ç±»åž‹ï¼štimeout, 404, anti_crawl, parse_error',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'error_detail',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='é”™è¯¯è¯¦æƒ…',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'retry_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='é‡\x8dè¯•æ¬¡æ•°',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_logs', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_created_at'), table_name='crawl_logs')
    op.drop_index(op.f('idx_error_type'), table_name='crawl_logs')
    op.drop_index(op.f('idx_level'), table_name='crawl_logs')
    op.drop_index(op.f('idx_resource_type'), table_name='crawl_logs')
    op.drop_index(op.f('idx_status'), table_name='crawl_logs')
    op.drop_index(op.f('idx_task_id'), table_name='crawl_logs')
    op.create_index('idx_cl_created_at', 'crawl_logs', ['created_at'], unique=False)
    op.create_index('idx_cl_error_type', 'crawl_logs', ['error_type'], unique=False)
    op.create_index('idx_cl_level', 'crawl_logs', ['level'], unique=False)
    op.create_index('idx_cl_resource_type', 'crawl_logs', ['resource_type'], unique=False)
    op.create_index('idx_cl_source_id', 'crawl_logs', ['source_id'], unique=False)
    op.create_index('idx_cl_status', 'crawl_logs', ['status'], unique=False)
    op.create_index('idx_cl_task_id', 'crawl_logs', ['task_id'], unique=False)
    op.create_table_comment(
        'crawl_logs',
        '爬虫日志表',
        existing_comment='çˆ¬è™«æ—¥å¿—è¡¨',
        schema=None
    )
    op.add_column('crawl_tasks', sa.Column('source_id', sa.String(length=32), nullable=True, comment='爬取源ID'))
    op.alter_column('crawl_tasks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='ä»»åŠ¡ID',
               existing_nullable=False)
    op.alter_column('crawl_tasks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='ä»»åŠ¡å\x90\x8dç§°',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'task_type',
               existing_type=mysql.ENUM('full', 'incremental', 'targeted', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ä»»åŠ¡ç±»åž‹',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='æ•°æ\x8d®æº\x90ï¼šwikipedia, douban',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'target_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='è®¡åˆ’çˆ¬å\x8f–æ•°é‡\x8f',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'completed_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='å·²å®Œæˆ\x90æ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'success_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='æˆ\x90åŠŸæ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'failed_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='å¤±è´¥æ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'status',
               existing_type=mysql.ENUM('pending', 'running', 'completed', 'failed', 'stopped', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('crawl_tasks', 'progress',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False,
               comment=None,
               existing_comment='è¿›åº¦ 0-100',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('crawl_tasks', 'config',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='ä»»åŠ¡é…\x8dç½®',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'started_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'completed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='åˆ›å»ºäºº',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crawl_tasks', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_created_at'), table_name='crawl_tasks')
    op.drop_index(op.f('idx_source'), table_name='crawl_tasks')
    op.drop_index(op.f('idx_status'), table_name='crawl_tasks')
    op.drop_index(op.f('idx_task_type'), table_name='crawl_tasks')
    op.create_index('idx_ct_created_at', 'crawl_tasks', ['created_at'], unique=False)
    op.create_index('idx_ct_source', 'crawl_tasks', ['source'], unique=False)
    op.create_index('idx_ct_source_id', 'crawl_tasks', ['source_id'], unique=False)
    op.create_index('idx_ct_status', 'crawl_tasks', ['status'], unique=False)
    op.create_index('idx_ct_task_type', 'crawl_tasks', ['task_type'], unique=False)
    op.create_table_comment(
        'crawl_tasks',
        '爬虫任务表',
        existing_comment='çˆ¬è™«ä»»åŠ¡è¡¨',
        schema=None
    )
    op.alter_column('person_relations', 'source_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='源人物ID',
               existing_comment='æº\x90äººç‰©ID',
               existing_nullable=False)
    op.alter_column('person_relations', 'target_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='目标人物ID',
               existing_comment='ç›®æ\xa0‡äººç‰©ID',
               existing_nullable=False)
    op.alter_column('person_relations', 'relation_type',
               existing_type=mysql.ENUM('MARRIED_TO', 'COLLABORATED_WITH', 'MENTOR_OF', 'RELATIVE', 'FRIEND', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='关系类型',
               existing_comment='å…³ç³»ç±»åž‹')
    op.alter_column('person_relations', 'properties',
               existing_type=mysql.JSON(),
               comment='关系属性',
               existing_comment='å…³ç³»å±žæ€§ï¼Œå¦‚ {start_date, end_date, status, work_id}',
               existing_nullable=True)
    op.alter_column('person_relations', 'confidence',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=False,
               comment='关系可信度',
               existing_comment='å…³ç³»å\x8f¯ä¿¡åº¦ 0-1',
               existing_server_default=sa.text("'1.00'"))
    op.alter_column('person_relations', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='数据来源',
               existing_comment='æ•°æ\x8d®æ\x9d¥æº\x90ï¼šwikipedia, manual, inferred',
               existing_nullable=True)
    op.alter_column('person_relations', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment=None,
               existing_comment='æ˜¯å\x90¦äººå·¥éªŒè¯\x81',
               existing_server_default=sa.text("'0'"))
    op.alter_column('person_relations', 'verified_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='éªŒè¯\x81äºº',
               existing_nullable=True)
    op.alter_column('person_relations', 'verified_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='éªŒè¯\x81æ—¶é—´',
               existing_nullable=True)
    op.alter_column('person_relations', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('person_relations', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_confidence'), table_name='person_relations')
    op.drop_index(op.f('idx_relation_type'), table_name='person_relations')
    op.drop_index(op.f('idx_source_id'), table_name='person_relations')
    op.drop_index(op.f('idx_target_id'), table_name='person_relations')
    op.create_index('idx_rel_confidence', 'person_relations', ['confidence'], unique=False)
    op.create_index('idx_rel_source_id', 'person_relations', ['source_id'], unique=False)
    op.create_index('idx_rel_target_id', 'person_relations', ['target_id'], unique=False)
    op.create_index('idx_rel_type', 'person_relations', ['relation_type'], unique=False)
    op.create_table_comment(
        'person_relations',
        '人物关系表',
        existing_comment='äººç‰©å…³ç³»è¡¨',
        schema=None
    )
    op.alter_column('person_works', 'person_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='äººç‰©ID',
               existing_nullable=False)
    op.alter_column('person_works', 'work_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='ä½œå“\x81ID',
               existing_nullable=False)
    op.alter_column('person_works', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='饰演角色/职位',
               existing_comment='é¥°æ¼”è§’è‰²/è\x81Œä½\x8d',
               existing_nullable=True)
    op.alter_column('person_works', 'role_type',
               existing_type=mysql.ENUM('actor', 'director', 'singer', 'composer', 'producer', 'writer', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='è§’è‰²ç±»åž‹',
               existing_nullable=True)
    op.alter_column('person_works', 'is_lead',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='是否主演',
               existing_comment='æ˜¯å\x90¦ä¸»æ¼”/ä¸»å”±',
               existing_server_default=sa.text("'0'"))
    op.alter_column('person_works', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('person_works', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_person_id'), table_name='person_works')
    op.drop_index(op.f('idx_work_id'), table_name='person_works')
    op.create_index('idx_pw_person_id', 'person_works', ['person_id'], unique=False)
    op.create_index('idx_pw_work_id', 'person_works', ['work_id'], unique=False)
    op.create_table_comment(
        'person_works',
        '人物作品关联表',
        existing_comment='äººç‰©ä½œå“\x81å…³è\x81”è¡¨',
        schema=None
    )
    op.alter_column('persons', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='唯一标识',
               existing_comment='å”¯ä¸€æ\xa0‡è¯†ï¼Œå¦‚ person_001',
               existing_nullable=False)
    op.alter_column('persons', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='中文名',
               existing_comment='ä¸\xadæ–‡å\x90\x8d',
               existing_nullable=False)
    op.alter_column('persons', 'name_en',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='英文名',
               existing_comment='è‹±æ–‡å\x90\x8d',
               existing_nullable=True)
    op.alter_column('persons', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='头像URL',
               existing_comment='å¤´åƒ\x8fURL',
               existing_nullable=True)
    op.alter_column('persons', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               comment='性别',
               existing_comment='æ€§åˆ«',
               existing_nullable=True)
    op.alter_column('persons', 'birth_date',
               existing_type=sa.DATE(),
               comment='出生日期',
               existing_comment='å‡ºç”Ÿæ—¥æœŸ',
               existing_nullable=True)
    op.alter_column('persons', 'birth_place',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='出生地',
               existing_comment='å‡ºç”Ÿåœ°',
               existing_nullable=True)
    op.alter_column('persons', 'nationality',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='国籍',
               existing_comment='å›½ç±\x8d',
               existing_nullable=True)
    op.alter_column('persons', 'height',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='身高(cm)',
               existing_comment='èº«é«˜(cm)',
               existing_nullable=True)
    op.alter_column('persons', 'summary',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='简介',
               existing_comment='ç®€ä»‹',
               existing_nullable=True)
    op.alter_column('persons', 'biography',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               comment='详细传记',
               existing_comment='è¯¦ç»†ä¼\xa0è®°',
               existing_nullable=True)
    op.alter_column('persons', 'popularity_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='知名度评分',
               existing_comment='çŸ¥å\x90\x8dåº¦è¯„åˆ† 0-100',
               existing_nullable=True)
    op.alter_column('persons', 'categories',
               existing_type=mysql.JSON(),
               comment='分类标签',
               existing_comment='åˆ†ç±»æ\xa0‡ç\xad¾ï¼Œå¦‚ ["singer", "actor"]',
               existing_nullable=True)
    op.alter_column('persons', 'status',
               existing_type=mysql.ENUM('active', 'pending', 'deleted', collation='utf8mb4_unicode_ci'),
               nullable=False,
               comment='数据状态',
               existing_comment='æ•°æ\x8d®çŠ¶æ€\x81',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('persons', 'data_quality_score',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               comment='数据质量评分',
               existing_comment='æ•°æ\x8d®è´¨é‡\x8fè¯„åˆ†',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='数据来源',
               existing_comment='æ•°æ\x8d®æ\x9d¥æº\x90ï¼šwikipedia, douban',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='原始爬取URL',
               existing_comment='åŽŸå§‹çˆ¬å\x8f–URL',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='关联的爬取任务ID',
               existing_comment='å…³è\x81”çš„çˆ¬å\x8f–ä»»åŠ¡ID',
               existing_nullable=True)
    op.alter_column('persons', 'raw_data',
               existing_type=mysql.JSON(),
               comment='保留原始爬取数据',
               existing_comment='ä¿\x9dç•™åŽŸå§‹çˆ¬å\x8f–æ•°æ\x8d®ï¼ˆæ¸…æ´—å‰\x8dï¼‰',
               existing_nullable=True)
    op.alter_column('persons', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('persons', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ft_summary'), table_name='persons', mysql_prefix='FULLTEXT')
    op.create_table_comment(
        'persons',
        '人物表',
        existing_comment='äººç‰©è¡¨',
        schema=None
    )
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='å”¯ä¸€æ\xa0‡è¯†',
               existing_nullable=False)
    op.alter_column('works', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('works', 'title_en',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='è‹±æ–‡æ\xa0‡é¢˜',
               existing_nullable=True)
    op.alter_column('works', 'type',
               existing_type=mysql.ENUM('album', 'movie', 'tv', 'drama', 'book', 'single', 'ep', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç±»åž‹',
               existing_nullable=True)
    op.alter_column('works', 'release_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='å\x8f‘å¸ƒæ—¥æœŸ',
               existing_nullable=True)
    op.alter_column('works', 'genre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='æµ\x81æ´¾/ç±»åž‹',
               existing_nullable=True)
    op.alter_column('works', 'rating',
               existing_type=mysql.DECIMAL(precision=3, scale=1),
               comment=None,
               existing_comment='è¯„åˆ† 0-10',
               existing_nullable=True)
    op.alter_column('works', 'poster',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='æµ·æŠ¥URL',
               existing_nullable=True)
    op.alter_column('works', 'summary',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='ç®€ä»‹',
               existing_nullable=True)
    op.alter_column('works', 'status',
               existing_type=mysql.ENUM('active', 'pending', 'deleted', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('works', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_release_date'), table_name='works')
    op.drop_index(op.f('idx_status'), table_name='works')
    op.drop_index(op.f('idx_title'), table_name='works')
    op.drop_index(op.f('idx_type'), table_name='works')
    op.create_index('idx_work_release_date', 'works', ['release_date'], unique=False)
    op.create_index('idx_work_status', 'works', ['status'], unique=False)
    op.create_index('idx_work_title', 'works', ['title'], unique=False)
    op.create_index('idx_work_type', 'works', ['type'], unique=False)
    op.create_table_comment(
        'works',
        '作品表',
        existing_comment='ä½œå“\x81è¡¨',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'works',
        'ä½œå“\x81è¡¨',
        existing_comment='作品表',
        schema=None
    )
    op.drop_index('idx_work_type', table_name='works')
    op.drop_index('idx_work_title', table_name='works')
    op.drop_index('idx_work_status', table_name='works')
    op.drop_index('idx_work_release_date', table_name='works')
    op.create_index(op.f('idx_type'), 'works', ['type'], unique=False)
    op.create_index(op.f('idx_title'), 'works', ['title'], unique=False)
    op.create_index(op.f('idx_status'), 'works', ['status'], unique=False)
    op.create_index(op.f('idx_release_date'), 'works', ['release_date'], unique=False)
    op.alter_column('works', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('works', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'status',
               existing_type=mysql.ENUM('active', 'pending', 'deleted', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('works', 'summary',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç®€ä»‹',
               existing_nullable=True)
    op.alter_column('works', 'poster',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='æµ·æŠ¥URL',
               existing_nullable=True)
    op.alter_column('works', 'rating',
               existing_type=mysql.DECIMAL(precision=3, scale=1),
               comment='è¯„åˆ† 0-10',
               existing_nullable=True)
    op.alter_column('works', 'genre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='æµ\x81æ´¾/ç±»åž‹',
               existing_nullable=True)
    op.alter_column('works', 'release_date',
               existing_type=sa.DATE(),
               comment='å\x8f‘å¸ƒæ—¥æœŸ',
               existing_nullable=True)
    op.alter_column('works', 'type',
               existing_type=mysql.ENUM('album', 'movie', 'tv', 'drama', 'book', 'single', 'ep', collation='utf8mb4_unicode_ci'),
               comment='ç±»åž‹',
               existing_nullable=True)
    op.alter_column('works', 'title_en',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='è‹±æ–‡æ\xa0‡é¢˜',
               existing_nullable=True)
    op.alter_column('works', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='æ\xa0‡é¢˜',
               existing_nullable=False)
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='å”¯ä¸€æ\xa0‡è¯†',
               existing_nullable=False)
    op.create_table_comment(
        'persons',
        'äººç‰©è¡¨',
        existing_comment='人物表',
        schema=None
    )
    op.create_index(op.f('ft_summary'), 'persons', ['summary', 'biography'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('persons', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('persons', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('persons', 'raw_data',
               existing_type=mysql.JSON(),
               comment='ä¿\x9dç•™åŽŸå§‹çˆ¬å\x8f–æ•°æ\x8d®ï¼ˆæ¸…æ´—å‰\x8dï¼‰',
               existing_comment='保留原始爬取数据',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='å…³è\x81”çš„çˆ¬å\x8f–ä»»åŠ¡ID',
               existing_comment='关联的爬取任务ID',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='åŽŸå§‹çˆ¬å\x8f–URL',
               existing_comment='原始爬取URL',
               existing_nullable=True)
    op.alter_column('persons', 'crawl_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='æ•°æ\x8d®æ\x9d¥æº\x90ï¼šwikipedia, douban',
               existing_comment='数据来源',
               existing_nullable=True)
    op.alter_column('persons', 'data_quality_score',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               comment='æ•°æ\x8d®è´¨é‡\x8fè¯„åˆ†',
               existing_comment='数据质量评分',
               existing_nullable=True)
    op.alter_column('persons', 'status',
               existing_type=mysql.ENUM('active', 'pending', 'deleted', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='æ•°æ\x8d®çŠ¶æ€\x81',
               existing_comment='数据状态',
               existing_server_default=sa.text("'pending'"))
    op.alter_column('persons', 'categories',
               existing_type=mysql.JSON(),
               comment='åˆ†ç±»æ\xa0‡ç\xad¾ï¼Œå¦‚ ["singer", "actor"]',
               existing_comment='分类标签',
               existing_nullable=True)
    op.alter_column('persons', 'popularity_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='çŸ¥å\x90\x8dåº¦è¯„åˆ† 0-100',
               existing_comment='知名度评分',
               existing_nullable=True)
    op.alter_column('persons', 'biography',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(collation='utf8mb4_unicode_ci'),
               comment='è¯¦ç»†ä¼\xa0è®°',
               existing_comment='详细传记',
               existing_nullable=True)
    op.alter_column('persons', 'summary',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='ç®€ä»‹',
               existing_comment='简介',
               existing_nullable=True)
    op.alter_column('persons', 'height',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='èº«é«˜(cm)',
               existing_comment='身高(cm)',
               existing_nullable=True)
    op.alter_column('persons', 'nationality',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='å›½ç±\x8d',
               existing_comment='国籍',
               existing_nullable=True)
    op.alter_column('persons', 'birth_place',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='å‡ºç”Ÿåœ°',
               existing_comment='出生地',
               existing_nullable=True)
    op.alter_column('persons', 'birth_date',
               existing_type=sa.DATE(),
               comment='å‡ºç”Ÿæ—¥æœŸ',
               existing_comment='出生日期',
               existing_nullable=True)
    op.alter_column('persons', 'gender',
               existing_type=mysql.ENUM('male', 'female', 'unknown', collation='utf8mb4_unicode_ci'),
               comment='æ€§åˆ«',
               existing_comment='性别',
               existing_nullable=True)
    op.alter_column('persons', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='å¤´åƒ\x8fURL',
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('persons', 'name_en',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='è‹±æ–‡å\x90\x8d',
               existing_comment='英文名',
               existing_nullable=True)
    op.alter_column('persons', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='ä¸\xadæ–‡å\x90\x8d',
               existing_comment='中文名',
               existing_nullable=False)
    op.alter_column('persons', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='å”¯ä¸€æ\xa0‡è¯†ï¼Œå¦‚ person_001',
               existing_comment='唯一标识',
               existing_nullable=False)
    op.create_table_comment(
        'person_works',
        'äººç‰©ä½œå“\x81å…³è\x81”è¡¨',
        existing_comment='人物作品关联表',
        schema=None
    )
    op.drop_index('idx_pw_work_id', table_name='person_works')
    op.drop_index('idx_pw_person_id', table_name='person_works')
    op.create_index(op.f('idx_work_id'), 'person_works', ['work_id'], unique=False)
    op.create_index(op.f('idx_person_id'), 'person_works', ['person_id'], unique=False)
    op.alter_column('person_works', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('person_works', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('person_works', 'is_lead',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='æ˜¯å\x90¦ä¸»æ¼”/ä¸»å”±',
               existing_comment='是否主演',
               existing_server_default=sa.text("'0'"))
    op.alter_column('person_works', 'role_type',
               existing_type=mysql.ENUM('actor', 'director', 'singer', 'composer', 'producer', 'writer', collation='utf8mb4_unicode_ci'),
               comment='è§’è‰²ç±»åž‹',
               existing_nullable=True)
    op.alter_column('person_works', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='é¥°æ¼”è§’è‰²/è\x81Œä½\x8d',
               existing_comment='饰演角色/职位',
               existing_nullable=True)
    op.alter_column('person_works', 'work_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='ä½œå“\x81ID',
               existing_nullable=False)
    op.alter_column('person_works', 'person_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='äººç‰©ID',
               existing_nullable=False)
    op.create_table_comment(
        'person_relations',
        'äººç‰©å…³ç³»è¡¨',
        existing_comment='人物关系表',
        schema=None
    )
    op.drop_index('idx_rel_type', table_name='person_relations')
    op.drop_index('idx_rel_target_id', table_name='person_relations')
    op.drop_index('idx_rel_source_id', table_name='person_relations')
    op.drop_index('idx_rel_confidence', table_name='person_relations')
    op.create_index(op.f('idx_target_id'), 'person_relations', ['target_id'], unique=False)
    op.create_index(op.f('idx_source_id'), 'person_relations', ['source_id'], unique=False)
    op.create_index(op.f('idx_relation_type'), 'person_relations', ['relation_type'], unique=False)
    op.create_index(op.f('idx_confidence'), 'person_relations', ['confidence'], unique=False)
    op.alter_column('person_relations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('person_relations', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('person_relations', 'verified_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='éªŒè¯\x81æ—¶é—´',
               existing_nullable=True)
    op.alter_column('person_relations', 'verified_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='éªŒè¯\x81äºº',
               existing_nullable=True)
    op.alter_column('person_relations', 'is_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='æ˜¯å\x90¦äººå·¥éªŒè¯\x81',
               existing_server_default=sa.text("'0'"))
    op.alter_column('person_relations', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='æ•°æ\x8d®æ\x9d¥æº\x90ï¼šwikipedia, manual, inferred',
               existing_comment='数据来源',
               existing_nullable=True)
    op.alter_column('person_relations', 'confidence',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               nullable=True,
               comment='å…³ç³»å\x8f¯ä¿¡åº¦ 0-1',
               existing_comment='关系可信度',
               existing_server_default=sa.text("'1.00'"))
    op.alter_column('person_relations', 'properties',
               existing_type=mysql.JSON(),
               comment='å…³ç³»å±žæ€§ï¼Œå¦‚ {start_date, end_date, status, work_id}',
               existing_comment='关系属性',
               existing_nullable=True)
    op.alter_column('person_relations', 'relation_type',
               existing_type=mysql.ENUM('MARRIED_TO', 'COLLABORATED_WITH', 'MENTOR_OF', 'RELATIVE', 'FRIEND', collation='utf8mb4_unicode_ci'),
               nullable=True,
               comment='å…³ç³»ç±»åž‹',
               existing_comment='关系类型')
    op.alter_column('person_relations', 'target_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='ç›®æ\xa0‡äººç‰©ID',
               existing_comment='目标人物ID',
               existing_nullable=False)
    op.alter_column('person_relations', 'source_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='æº\x90äººç‰©ID',
               existing_comment='源人物ID',
               existing_nullable=False)
    op.create_table_comment(
        'crawl_tasks',
        'çˆ¬è™«ä»»åŠ¡è¡¨',
        existing_comment='爬虫任务表',
        schema=None
    )
    op.drop_index('idx_ct_task_type', table_name='crawl_tasks')
    op.drop_index('idx_ct_status', table_name='crawl_tasks')
    op.drop_index('idx_ct_source_id', table_name='crawl_tasks')
    op.drop_index('idx_ct_source', table_name='crawl_tasks')
    op.drop_index('idx_ct_created_at', table_name='crawl_tasks')
    op.create_index(op.f('idx_task_type'), 'crawl_tasks', ['task_type'], unique=False)
    op.create_index(op.f('idx_status'), 'crawl_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_source'), 'crawl_tasks', ['source'], unique=False)
    op.create_index(op.f('idx_created_at'), 'crawl_tasks', ['created_at'], unique=False)
    op.alter_column('crawl_tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('crawl_tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crawl_tasks', 'created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='åˆ›å»ºäºº',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'started_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'config',
               existing_type=mysql.JSON(),
               comment='ä»»åŠ¡é…\x8dç½®',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'progress',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True,
               comment='è¿›åº¦ 0-100',
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('crawl_tasks', 'status',
               existing_type=mysql.ENUM('pending', 'running', 'completed', 'failed', 'stopped', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('crawl_tasks', 'failed_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='å¤±è´¥æ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'success_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='æˆ\x90åŠŸæ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'completed_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='å·²å®Œæˆ\x90æ•°é‡\x8f',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_tasks', 'target_count',
               existing_type=mysql.INTEGER(),
               comment='è®¡åˆ’çˆ¬å\x8f–æ•°é‡\x8f',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='æ•°æ\x8d®æº\x90ï¼šwikipedia, douban',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'task_type',
               existing_type=mysql.ENUM('full', 'incremental', 'targeted', collation='utf8mb4_unicode_ci'),
               comment='ä»»åŠ¡ç±»åž‹',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='ä»»åŠ¡å\x90\x8dç§°',
               existing_nullable=True)
    op.alter_column('crawl_tasks', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='ä»»åŠ¡ID',
               existing_nullable=False)
    op.drop_column('crawl_tasks', 'source_id')
    op.create_table_comment(
        'crawl_logs',
        'çˆ¬è™«æ—¥å¿—è¡¨',
        existing_comment='爬虫日志表',
        schema=None
    )
    op.drop_index('idx_cl_task_id', table_name='crawl_logs')
    op.drop_index('idx_cl_status', table_name='crawl_logs')
    op.drop_index('idx_cl_source_id', table_name='crawl_logs')
    op.drop_index('idx_cl_resource_type', table_name='crawl_logs')
    op.drop_index('idx_cl_level', table_name='crawl_logs')
    op.drop_index('idx_cl_error_type', table_name='crawl_logs')
    op.drop_index('idx_cl_created_at', table_name='crawl_logs')
    op.create_index(op.f('idx_task_id'), 'crawl_logs', ['task_id'], unique=False)
    op.create_index(op.f('idx_status'), 'crawl_logs', ['status'], unique=False)
    op.create_index(op.f('idx_resource_type'), 'crawl_logs', ['resource_type'], unique=False)
    op.create_index(op.f('idx_level'), 'crawl_logs', ['level'], unique=False)
    op.create_index(op.f('idx_error_type'), 'crawl_logs', ['error_type'], unique=False)
    op.create_index(op.f('idx_created_at'), 'crawl_logs', ['created_at'], unique=False)
    op.alter_column('crawl_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('crawl_logs', 'retry_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='é‡\x8dè¯•æ¬¡æ•°',
               existing_server_default=sa.text("'0'"))
    op.alter_column('crawl_logs', 'error_detail',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='é”™è¯¯è¯¦æƒ…',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'error_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='é”™è¯¯ç±»åž‹ï¼štimeout, 404, anti_crawl, parse_error',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'message',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='æ—¥å¿—æ¶ˆæ\x81¯',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'duration_ms',
               existing_type=mysql.INTEGER(),
               comment='è€—æ—¶(ms)',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'status',
               existing_type=mysql.ENUM('success', 'failed', 'retry', 'pending', collation='utf8mb4_unicode_ci'),
               comment='çŠ¶æ€\x81',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='æ“\x8dä½œï¼šdownload, parse, store, skip',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'resource_type',
               existing_type=mysql.ENUM('person', 'work', 'page', collation='utf8mb4_unicode_ci'),
               comment='èµ„æº\x90ç±»åž‹',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'resource_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='èµ„æº\x90å\x90\x8dç§°',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'resource_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='çˆ¬å\x8f–URL',
               existing_nullable=True)
    op.alter_column('crawl_logs', 'level',
               existing_type=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'DEBUG', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'INFO'"))
    op.alter_column('crawl_logs', 'task_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='ä»»åŠ¡ID',
               existing_nullable=False)
    op.drop_column('crawl_logs', 'details')
    op.drop_column('crawl_logs', 'stage')
    op.drop_column('crawl_logs', 'source_id')
    op.create_table_comment(
        'audit_logs',
        'å®¡è®¡æ—¥å¿—è¡¨',
        existing_comment='审计日志表',
        schema=None
    )
    op.drop_index('idx_al_user_id', table_name='audit_logs')
    op.drop_index('idx_al_resource', table_name='audit_logs')
    op.drop_index('idx_al_created_at', table_name='audit_logs')
    op.drop_index('idx_al_action', table_name='audit_logs')
    op.create_index(op.f('idx_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('audit_logs', 'new_values',
               existing_type=mysql.JSON(),
               comment='ä¿®æ”¹å\x90Žçš„å€¼',
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_values',
               existing_type=mysql.JSON(),
               comment='ä¿®æ”¹å‰\x8dçš„å€¼',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='èµ„æº\x90ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='èµ„æº\x90ç±»åž‹ï¼šperson/work/relation',
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='æ“\x8dä½œï¼šCREATE/UPDATE/DELETE/LOGIN',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='æ“\x8dä½œç”¨æˆ·',
               existing_nullable=True)
    op.create_table_comment(
        'admin_users',
        'ç®¡ç\x90†å‘˜ç”¨æˆ·è¡¨',
        existing_comment='管理员用户表',
        schema=None
    )
    op.drop_index('idx_au_username', table_name='admin_users')
    op.drop_index('idx_au_role', table_name='admin_users')
    op.drop_index('idx_au_is_active', table_name='admin_users')
    op.create_index(op.f('idx_username'), 'admin_users', ['username'], unique=False)
    op.create_index(op.f('idx_role'), 'admin_users', ['role'], unique=False)
    op.create_index(op.f('idx_is_active'), 'admin_users', ['is_active'], unique=False)
    op.alter_column('admin_users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('admin_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('admin_users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('admin_users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('admin_users', 'permissions',
               existing_type=mysql.JSON(),
               comment='æ\x9dƒé™\x90åˆ—è¡¨',
               existing_nullable=True)
    op.alter_column('admin_users', 'role',
               existing_type=mysql.ENUM('super_admin', 'data_admin', 'operator', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'operator'"))
    op.create_table('schema_migrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('executed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('execution_time_ms', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('version'), 'schema_migrations', ['version'], unique=True)
    op.drop_index('idx_cs_type', table_name='crawl_sources')
    op.drop_index('idx_cs_status', table_name='crawl_sources')
    op.drop_index('idx_cs_health', table_name='crawl_sources')
    op.drop_table('crawl_sources')
    op.drop_index('idx_css_stat_date', table_name='crawl_source_stats')
    op.drop_index('idx_css_source_id', table_name='crawl_source_stats')
    op.drop_table('crawl_source_stats')
    op.drop_index('idx_csch_task_type', table_name='crawl_schedules')
    op.drop_index('idx_csch_next_run', table_name='crawl_schedules')
    op.drop_index('idx_csch_enabled', table_name='crawl_schedules')
    op.drop_table('crawl_schedules')
    op.drop_index('idx_csr_status', table_name='crawl_schedule_runs')
    op.drop_index('idx_csr_started_at', table_name='crawl_schedule_runs')
    op.drop_index('idx_csr_schedule_id', table_name='crawl_schedule_runs')
    op.drop_table('crawl_schedule_runs')
    # ### end Alembic commands ###
